Allow to pass doctest specific options to each runner
sorbet/sorbet pull request #3515
Opened 2020-10-16 16:35 UTC by garuma

### Motivation
Use the [DOCTEST_CONFIG_NO_UNPREFIXED_OPTIONS](https://github.com/onqtam/doctest/blob/master/doc/markdown/configuration.md#doctest_config_no_unprefixed_options) define to allow passing doctest specific options (which are prefixed with "--dt-" to avoid colliding with any current/future custom command line flags the runner may have).

As a rationale, this allows to use options such as "--no-colors" (specified as "--dt-no-colors") to force disable escape sequences when doctest TTY recognition fails to work (which is the case if you are trying to debug from VSCode).

### Test plan

None

2020-10-16 16:37 UTC, jez commented
Passing to jvilk because he knows more about doctest than me.

2020-10-16 17:03 UTC, jvilk-stripe requested changes
Thanks for making this change!

We currently have all of the DOCTEST-specific defines specified in Bazel so that all binaries using doctest pick them up:
https://github.com/sorbet/sorbet/blob/b21d4db9/third_party/doctest.BUILD#L21

For the NO_UNPREFIXED_OPTIONS define, the documentation says:
> This should be defined only in the source file where the library is implemented (it's relevant only there).

So I think you can add this define to the linked line and it'll just work (as that's the bazel target containing the doctest implementation).

2020-10-19 12:58 UTC, garuma commented
@jvilk-stripe pushed updated commit with define in Bazel, in my testing I had to specify it in the main doctest target for it to work properly, not sure if I'm missing something as the runners pull from both the main target and custom_main:
https://github.com/sorbet/sorbet/blob/360067b73e7fe362ba34e3b28d4862cd57b0cdc4/test/BUILD#L54-L55

2020-10-20 18:39 UTC, jvilk-stripe approved these changes

2020-10-20 19:30 UTC, garuma commented
Closed in favor of https://github.com/sorbet/sorbet/pull/3539

2020-10-20 19:30 UTC, closed without merging