[WIP] Compute Symbol::externalType serially.
sorbet/sorbet pull request #3544
Opened 2020-10-21 01:12 UTC by jvilk-stripe

Compute Symbol::externalType serially.

Delurks an atomic operation that 1) complicates an effort to use tagged pointers for TypedPtr and 2) is not actually needed!

### Motivation

Makes it much simpler to transition to a tagged TypedPtr, and removes a lurky abstraction-breaking line of code.

### Test plan

Covered by existing tests.

2020-10-21 01:15 UTC, jvilk-stripe commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_IEzuiY2QeqYRK7

2020-10-21 02:13 UTC, jez commented
I am curious to see if this is actually faster. I have been bitten by this atomic set before

2020-10-21 05:06 UTC, jvilk-stripe commented
I'm not really expecting a speedup on this at all (this function isn't hot on profiles), but it _does_ unlock some future optimizations to TypePtr! :D

2020-10-21 05:24 UTC, jvilk-stripe commented
looks like it's buggy though! :)  https://go/builds/bui_IF3hNs0oYOv23A

2020-10-26 04:25 UTC, jvilk-stripe commented
~Clean build at http://go/builds/bui_IGuvFH76QGZWDQ

The type errors are due to an unrelated FileUtils change we haven't merged yet to Stripe's codebase.

This is now ready for review.

2020-10-26 04:32 UTC, jvilk-stripe commented
The eager computation completes in a negligible amount of time.

2020-10-26 22:00 UTC, elliottt requested changes

2020-10-26 23:03 UTC, elliottt approved these changes
Cleared this up over zoom: I missed the fact that we were calling `unsafeComputeExternalType` in more than one place.

2020-10-27 00:20 UTC, merged