[WIP] Autoloader support for --stripe-packages
sorbet/sorbet pull request #3585
Opened 2020-10-28 18:52 UTC by aisamanra

### Motivation

### Test plan

See included automated tests.

2020-10-30 18:54 UTC, aisamanra commented on main/realmain.cc
> +                if (tree.file.data(gs).isRBI() || tree.file.data(gs).isPackage()) {
This just means we don't generate autoloader information for `__package.rbi` files.

2020-10-30 18:54 UTC, aisamanra commented on main/realmain.cc
> +            indexed = pipeline::package(*gs, move(indexed), opts, *workers);
The `pipeline::package` function already handles "do not run if `--stripe-packages` is not supplied," so we don't need to do any conditional logic here.

2020-10-30 18:55 UTC, aisamanra commented on packager/packager.cc
> +    if (file.file.data(ctx).originalSigil < core::StrictLevel::Strict) {
We set the `strictLevel` lower artificially for autogen so we don't get errors even from invalid code. That means that in autogen every `__package.rb` file would raise this error. We can sidestep that by checking the `originalSigil`, which is retained even if `strictLevel` is set lower.

2020-11-05 20:03 UTC, jvilk-stripe requested changes
My only hard request is to change the `isPackage()` helper, which could cause issues down the line / is more expensive than it needs to be.

Everything else looks good to me. Thanks for adding tests!

2020-11-09 17:31 UTC, jvilk-stripe approved these changes
LGTM

2020-11-09 17:31 UTC, jvilk-stripe commented on main/autogen/autoloader.cc
> +    return !nd.qname.nameParts.empty() &&
```suggestion
    return !nd.qname.empty() &&
```

2020-11-10 18:33 UTC, aisamanra commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build result here:

→ https://go/builds/bui_IMlBHuSzWpVO0F

2020-11-12 00:30 UTC, aisamanra commented
Pay-server prework is landing so I'm merging this.

2020-11-12 00:30 UTC, merged