Fix more than one unnamed parameter in method definition
sorbet/sorbet pull request #3879
Opened 2021-01-11 21:39 UTC by tvallois

Hi, first thanks for Sorbet, an amazing tool for ruby developers. :+1: 

In this change, i'm looking at the number of parameters equal to underscore because it is the only parameter that can occur multiple times in a same function in ruby.
Looking at this comment https://github.com/sorbet/sorbet/issues/3674#issuecomment-728674364, a suggestion was to remove the function from hidden-definitions, that's what i've done in this PR.

### Motivation

Since we're upgraded sorbet-runtime from 0.5.5944 to the latest version, we're unable to regenerate rbis anymore. We have the error describe in the issue above.

### Test plan

See included automated tests.

2021-01-16 00:48 UTC, elliottt requested changes
Thanks!

Could you add a test in `/gems/sorbet/test/snapshot/partial` that shows that methods with multiple unnamed arguments don't make it into reflection.rbi?

2021-01-18 15:16 UTC, tvallois commented
Hi,

Should be good now ! Thanks for review @elliottt

2021-01-19 04:52 UTC, jez commented on gems/sorbet/test/snapshot/partial/unnamed_arguments/src/src.rb
> +  end
Do you want to add another method to this test case in a way that Sorbet can't see the definition statically?

```suggestion
  def first_method(_, _)
    nil
  end
  
  define_method(:second_method) do |_, _|
    nil
  end
```

2021-01-19 04:52 UTC, jez commented
Thanks for the PR. It seems to me that a better solution would be to rename the positional arguments from `_, _` to `_1, _2` if we detect that they're duplicated, instead of just not serializing the method.

Sorbet doesn't actually care about the name of positional arguments to a method, just how many there are (and if there's a sig, that they match what's mentioned in the sig).

While I see that the current behavior is obviously bad (`_, _` will immediately generate an error), I wonder if while you're here that you want to take a shot at fixing the root of the problem, rather than just treating the symptoms?

2021-01-19 09:10 UTC, tvallois commented
> Thanks for the PR. It seems to me that a better solution would be to rename the positional arguments from `_, _` to `_1, _2` if we detect that they're duplicated, instead of just not serializing the method.
> 
> Sorbet doesn't actually care about the name of positional arguments to a method, just how many there are (and if there's a sig, that they match what's mentioned in the sig).
> 
> While I see that the current behavior is obviously bad (`_, _` will immediately generate an error), I wonder if while you're here that you want to take a shot at fixing the root of the problem, rather than just treating the symptoms?

hey @jez , definitely, it was my first idea to rename the positional arguments from `_, _` to `_1, _2`. Do you want me to create a new merge request to apply those changes or should i do everything on this one?

2021-03-05 19:57 UTC, jez commented
Heads up I fixed this in a different way in #4055

2021-03-05 21:21 UTC, jez commented
Closed via #4055

2021-03-05 21:21 UTC, closed without merging