[wip] only allow symbol-typed names for props and consts
sorbet/sorbet pull request #3885
Opened 2021-01-13 18:13 UTC by ezra-stripe

### Motivation

### Test plan

See included automated tests.

2021-01-13 18:20 UTC, jez commented
(removing my review—feel free to re-request once non-wip)

2021-01-13 19:43 UTC, ezra-stripe commented
cc @trevor-stripe

2021-01-13 19:49 UTC, elliottt commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_IkkqfZWf0w49Vk
→ https://go/builds/bui_IkkrGiVssXJ0jT

2021-01-13 19:51 UTC, ezra-stripe commented
> I've kicked off a test run for the current PR. When the build
> finishes, I'll share with you whether or how it failed. Thanks!
> 
> Stripe employees can see the build results here:
> 
> → https://go/builds/bui_IkkqfZWf0w49Vk
> → https://go/builds/bui_IkkrGiVssXJ0jT

Thanks for that. I'm still interested in discussing whether or not we want the change though. WDYT?

2021-01-13 21:10 UTC, elliottt requested changes
@ezra-stripe could you add a test for each in `gems/sorbet-runtime/test/types/struct.rb` showing what the behavior of these methods is with `String` arguments? It would be good to make sure that we're raising runtime errors as well.

2021-01-25 21:11 UTC, elliottt commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_IpGtBGTUnCkART
→ https://go/builds/bui_IpGtNeChbo1Rd1

2021-01-25 21:35 UTC, elliottt approved these changes
Thanks for the test!

2021-01-25 21:35 UTC, merged