add a T::Configuration option for VM prop serde and appropriate modifications
sorbet/sorbet pull request #4171
Opened 2021-04-22 20:15 UTC by froydnj

### Motivation

We have some changes to prop serialization/deserialization that are faster than the `sorbet-runtime` codegen and avoid the use of `class_eval`.  To be able to reasonably test those changes, we'd like to add a `T::Configuration` option that selects between the status quo and the accelerated routines.

### Test plan

There's not much to test here.  I did verify that the `test` and `test_vm_serde` Rakefile targets pass (well, subject to error handling problems with the VM-defined routines) on an appropriately configured Ruby.

2021-04-22 22:24 UTC, elliottt requested changes
This makes sense to me. Could you point me to the definition of `generate2`? I was curious to see how it differed from the existing generate/eval implementation.

Would you mind adding a test to the runtime test suite that exercises the errors we'd expect to see if the vm doesn't support deserialization?

2021-04-22 22:24 UTC, elliottt commented on gems/sorbet-runtime/lib/types/props/serializable.rb
> +  end
Where is `generate2` defined?

2021-04-23 15:39 UTC, froydnj commented
> This makes sense to me. Could you point me to the definition of `generate2`? I was curious to see how it differed from the existing generate/eval implementation.

Pointed this out offline, since it's currently in Stripe-internal systems.

> Would you mind adding a test to the runtime test suite that exercises the errors we'd expect to see if the vm doesn't support deserialization?

Pushed bits with a test and a reworking of the Rakefile to placate Sorbet.

2021-04-26 21:06 UTC, elliottt approved these changes

2021-04-26 21:11 UTC, merged