Fix Pathname#find signature
sorbet/sorbet pull request #4214
Opened 2021-05-14 19:47 UTC by Bo98

### Motivation
`ignore_error` is an optional keyword argument, as documented at https://ruby-doc.org/stdlib-2.6.3/libdoc/pathname/rdoc/Pathname.html#method-i-find.

2021-05-14 19:51 UTC, aprocter-stripe commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_JU5Ds5xOseHCyB
→ https://go/builds/bui_JU5DJsrW7QTTlX

2021-05-14 23:31 UTC, aprocter-stripe requested changes
It looks like the tests are failing because `find` has more than one overloaded signature, which isn't compatible with keyword args. If the return type weren't dependent on the choice of overloading, I suppose we could just make the `blk` nilable instead of relying on overloading, but as things stand I'm not sure how to make it work without falling back to `returns(T.untyped)` in all cases.

@jez thoughts on how to make this work? (I might very well be missing something!)

2021-05-14 23:47 UTC, jez commented
> thoughts on how to make this work

you will have to either remove the overloads and make it have a single signature, or you will have to make it overloaded without keyword arguments by e.g. making an overly wide signature that accepts any keyword args or any args.

2021-05-15 01:09 UTC, Bo98 commented
I completely missed the double signature here - my bad.

I'm not sure I understand why it's `T.untyped`. When does `Pathname.find` with a block return anything?

I'm leaning torwards a nilable block with a nilable return value. In fact, that's exactly how it's defined for `Find.find`: https://github.com/sorbet/sorbet/blob/4f146522e25047f6527a98797672f9b1c462eced/rbi/stdlib/find.rbi#L32-L39

2021-05-17 23:03 UTC, aprocter-stripe commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_JVFyWvPYAFjm6Z
→ https://go/builds/bui_JVFywmq6z2E2HW

2021-05-17 23:35 UTC, aprocter-stripe commented
> I'm leaning torwards a nilable block with a nilable return value. In fact, that's exactly how it's defined for `Find.find`:

Ah, good find (no pun intended)!

The `nilable(Enumerator)` formulation looks reasonable to me. Thanks for the fix!

2021-05-17 23:35 UTC, aprocter-stripe approved these changes

2021-05-17 23:35 UTC, merged