Add the missing Enumerable#chain method and signature
sorbet/sorbet pull request #4219
Opened 2021-05-18 15:54 UTC by lugray

[Enumerable#chain](https://ruby-doc.org/core-2.6/Enumerable.html#method-i-chain) introduced in ruby 2.6 wasn't defined.

2021-05-18 23:31 UTC, aprocter-stripe commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_JVdeRDEvcFRp9s
→ https://go/builds/bui_JVdeWqgtKF93DP

2021-05-18 23:53 UTC, aprocter-stripe requested changes
Thanks for the rbi update! I think this signature seems reasonable.

Looks like tests are failing because output expectations for the hidden method finder need to be updated. Would you mind running `gems/sorbet/test/hidden-method-finder/update_hidden_methods_exp.sh` and committing the changes it makes? I should be able to stamp and merge this once that's fixed.

2021-05-19 12:15 UTC, lugray commented
I had to run `PATH="./:$PATH" gems/sorbet/test/hidden-method-finder/update_hidden_methods_exp.sh` as I don't generally have `bazel` on my PATH, but otherwise all seemed to go well and the diff makes sense. Thanks for the help.

2021-05-19 18:45 UTC, aprocter-stripe approved these changes
Thanks again @lugray!

2021-05-19 18:45 UTC, merged