Auto correct initialize sigs not returning void
sorbet/sorbet pull request #4533
Opened 2021-08-25 19:46 UTC by vinistock

Closes #2929

Add an error and auto-correct for `initialize` signatures that don't return `void`.

The first commit contains the entire implementation. The second one is just fixing internal RBIs that weren't returning `void` for initializers.

### Motivation

The recommendation is to have all initializers return `void`, so we should help enforce the correct behaviour.

### Test plan

See included automated tests.

2021-09-07 19:15 UTC, froydnj commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_KBWoFXxlKtDNVT
→ https://go/builds/bui_KBWpkTQx9Z1ySs

2021-09-07 19:56 UTC, froydnj requested changes
Thanks for the changes; sorry about the delay in getting feedback to you.  One more wrinkle:

```ruby
# typed: true

class Params < T::Struct
  extend T::Sig
  prop :raw, T.nilable(String)

  sig {params(hash: T::Hash[Symbol, T.untyped]).returns(Params)}
  def self.initialize(hash)
    Params.new(raw: hash[:raw])
  end
end
```

`self.initialize` should not be auto-corrected to return void.  (I think that means that the rewriter should not fire entirely on `self.initialize`?)

2021-09-07 20:27 UTC, froydnj commented
Another one:

```ruby
sig do
  params(
    path: String,
    key: String
  )
  .returns(T.self_type)
  .checked(:tests)
end
def initialize(path, key)
  ...
end
```

should not be auto-corrected to `.void.checked(:tests)`, but to:

```
  .void
  .checked(:tests)
```

This is a Stripe-specific rubocop, but it seems somewhat reasonable to implement here: the autocorrect shouldn't change the formatting of items before or after the `.returns/.void`.

2021-09-08 15:35 UTC, vinistock commented
The latest commit contains the fix for line breaks after the returns statement. Thanks for all the attention to the detail, this is looking a lot more robust than it was in the beginning 🚀.

2021-09-09 17:15 UTC, froydnj commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_KCFKcvo1eBGWOO
→ https://go/builds/bui_KCFKSvmff2tVVt

2021-09-09 19:16 UTC, froydnj commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_KCHITQ2h4yfhWX
→ https://go/builds/bui_KCHI2fKw6Fz1P1

2021-09-09 19:25 UTC, froydnj approved these changes
Thank you!

2021-09-09 19:29 UTC, merged

2021-09-10 15:03 UTC, dduugg commented
This is causing errors in `sorbet-typed`, e.g.:

```
./sorbet/rbi/sorbet-typed/lib/rainbow/all/rainbow.rbi:33: The initialize method should always return void https://srb.help/3510
    33 |      sig { params(ground: Symbol, num: Integer).returns(Indexed) }
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    ./sorbet/rbi/sorbet-typed/lib/rainbow/all/rainbow.rbi:33: Replace with params(ground: Symbol, num: Integer).void
    33 |      sig { params(ground: Symbol, num: Integer).returns(Indexed) }
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

(Would it be possible to add definitely-typed to the test suite, in the manner of testing against Stripe's codebase?)