Report a better error when type aliases are exported in --stripe-packages mode
sorbet/sorbet pull request #4937
Opened 2021-12-01 04:09 UTC by aadi-stripe

### Motivation

In `--stripe-packages` mode, when a constant exported by a package is a type alias, we get error [5034](https://sorbet.org/docs/error-reference#5028) due to the fact that the packager's virtual AST node inserted effectively becomes a reassignment of a type-alias. We have ratcheted against this behavior in the Stripe codebase for now, but when we launch `--stripe-packages`, we may remove this ratchet. In that situation, we want to throw a more user-friendly error.

### Test plan

See included automated tests.

2021-12-01 04:09 UTC, aadi-stripe commented
cc @nroman-stripe

2021-12-01 23:39 UTC, aadi-stripe commented
Also cc @jvilk-stripe

2021-12-02 18:56 UTC, ngroman requested changes
Logic looks reasonable. But need to fix the duplicate method.

2021-12-02 18:56 UTC, ngroman commented on core/Files.h
> +    };
`isPackage()` is already a method on `File`.  This is not needed.

2021-12-02 18:56 UTC, ngroman commented on resolver/resolver.cc
> +                    e.setHeader("Exporting a type alias is not allowed");
```suggestion
                    e.setHeader("Exporting a type alias is not allowed in package specifications");
```

2021-12-02 19:58 UTC, aadi-stripe commented
ptal @ngroman

2021-12-02 20:46 UTC, ngroman approved these changes
Looks good from my end

2021-12-02 20:48 UTC, merged