Substantially better error recovery for method args
sorbet/sorbet pull request #5114
Opened 2022-01-14 09:56 UTC by jez

### Motivation

This causes a huge source of pain when using Sorbet in large codebases, because
small edits frequently cause large swaths of a file to be thrown away.

### Test plan

See included automated tests.

2022-01-14 17:52 UTC, elliottt requested changes
Looking forward to using this!

My one concern right now is that there are a fair number of productions that match `error` and don't explicitly add errors. Either we should add comments explaining why it's not necessary to do so in those cases, or explicitly add errors.

2022-01-14 17:52 UTC, elliottt commented on parser/parser/cc/grammars/typedruby.ypp
> +                    }
Does this rule need to add an error?

2022-01-14 17:52 UTC, elliottt commented on parser/parser/cc/grammars/typedruby.ypp
> +                      $$ = $1;
Should this rule add an error?

2022-01-14 17:52 UTC, elliottt commented on parser/parser/cc/grammars/typedruby.ypp
> +                    }
Should this rule add an error?

2022-01-15 02:21 UTC, jez commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_KxxpXn6VKL0Did
→ https://go/builds/bui_Kxxpw5kIvgI7Ey

2022-01-25 00:08 UTC, elliottt approved these changes

2022-01-25 00:10 UTC, elliottt commented
After discussion from a DM: I misunderstood how `error` works in bison, and assumed that it would eat the parse error like it does in [happy](https://www.haskell.org/happy/doc/html/sec-error.html). As errors will be raised in all these cases, all my previous comments don't apply 👍

2022-01-25 06:30 UTC, merged