Add CSV::Row as a return type for CSV.read
sorbet/sorbet pull request #5136
Opened 2022-01-19 22:52 UTC by XanderStrike

Resolves #5131

### Motivation

`CSV::Row` is a valid return type when the `headers:` keyword argument is provided to
`.read`, it provides a superset of functionality over the array, such as
fetching elements by string arguments, or converting the row to a hash with
`to_hash`.

### Test plan

Wrote a [small file](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0ACSV.read%28%22filename.csv%22%2C%20headers%3A%20%3Afirst_row%29.each_with_object%28%7B%7D%29%20do%20%7Crow%2C%20obj%7C%0A%20%20obj%5Brow.fetch%28%22id%22%29%5D%20%3D%20row.to_hash%0Aend) that triggers the erroneous errors. 

Pre-patched sorbet throws errors, post-patched sorbet does not. 🎉 

Let me know if there are automated tests for this, I couldn't find 'em.

2022-01-20 01:24 UTC, elliottt commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Kzp1ow5xOo5pwE
→ https://go/builds/bui_Kzp1ub7psvUL7h

2022-01-20 18:27 UTC, elliottt commented
This raised some problems on Stripe's codebase. When using the `[]` method on the result of `CSV.read`, the result is now `T.untyped` instead of a `T.nilable(String)` which raises new errors when calling `T.must` on `T.untyped`. What do you think about also adding a signature on `CSV#row` to avoid this problem?

2022-01-20 18:28 UTC, elliottt requested changes
This raised some problems on Stripe's codebase. When using the `[]` method on the result of `CSV.read`, the result is now T.untyped instead of a `T.nilable(String)` which raises new errors when calling `T.must` on `T.untyped`. What do you think about also adding a signature on `CSV#row` to avoid this problem?

2022-01-21 22:40 UTC, XanderStrike commented
Thanks for checking that! I think it previously worked by accident, depending on CSV::Row returning untyped for everything. I realized I actually need it to return `CSV::Table` (which then enumerates over rows).

I was not able to reproduce the issue you're talking about, but I with these changes I have verified that `[]`, `field`, and `fetch` are returning `T.nilable(String)` for `CSV::Row` type objects.

```
CSV.read("filename.csv", headers: :first_line).each_with_object({}) do |row, obj|
  T.reveal_type(row) # T.any(CSV::Row, T::Array[T.untyped])

  cast_row = T.cast(row, CSV::Row)
  obj[cast_row["id"]] = cast_row.to_hash

  T.reveal_type(cast_row) # CSV::Row
  T.reveal_type(cast_row["hello"]) # T.nilable(String)
  T.reveal_type(cast_row.fetch("hello")) # T.nilable(String)
  T.reveal_type(cast_row.field("hello")) # T.nilable(String)
  puts T.must(cast_row["hello"]).chomp
end
```

If this doesn't fix the issue you're talking about, could you provide a code snippet that I could use?

2022-01-24 17:58 UTC, elliottt commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_L1ZyqRAI1YDlWD
→ https://go/builds/bui_L1ZyLxcqiglsAY

2022-01-25 17:10 UTC, elliottt commented
This last run raised more errors, as there's quite a bit of code that assumes the rows returned are arrays. I'll bring this PR up with the rest of the team at stripe and see what the best next steps are.

2024-03-06 17:29 UTC, XanderStrike commented
Closing to clean up my PR list.

2024-03-06 17:29 UTC, closed without merging