Fix parents for Net::IMAP structs
sorbet/sorbet pull request #5139
Opened 2022-01-20 15:15 UTC by Morriar

### Motivation

According to documentation:

* [Net::IMAP::BodyTypeAttachment](https://ruby-doc.org/stdlib-2.7.2/libdoc/net/imap/rdoc/Net/IMAP/BodyTypeAttachment.html)
* [Net::IMAP::BodyTypeBasic](https://ruby-doc.org/stdlib-2.7.2/libdoc/net/imap/rdoc/Net/IMAP/BodyTypeBasic.html)
* [Net::IMAP::BodyTypeExtension](https://ruby-doc.org/stdlib-2.7.2/libdoc/net/imap/rdoc/Net/IMAP/BodyTypeExtension.html)
* [Net::IMAP::BodyTypeMessage](https://ruby-doc.org/stdlib-2.7.2/libdoc/net/imap/rdoc/Net/IMAP/BodyTypeMessage.html)
* [Net::IMAP::BodyTypeMultipart](https://ruby-doc.org/stdlib-2.7.2/libdoc/net/imap/rdoc/Net/IMAP/BodyTypeMultipart.html)
* [Net::IMAP::BodyTypeText](https://ruby-doc.org/stdlib-2.7.2/libdoc/net/imap/rdoc/Net/IMAP/BodyTypeText.html)

### Test plan

See included automated tests.

2022-01-20 15:19 UTC, froydnj commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_L02V0CKmewN0PC
→ https://go/builds/bui_L02VNDaP0ArCvD

2022-01-20 15:22 UTC, froydnj requested changes
Looks like the RBI files need declaration for the `Elem` type member.

2022-01-20 22:42 UTC, Morriar commented
@froydnj I added the missing type members 👍

2022-01-21 13:48 UTC, froydnj commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_L0OGOlzuti4lQm
→ https://go/builds/bui_L0OGTaKEauDyW4

2022-01-21 13:59 UTC, froydnj approved these changes
Thanks!

2022-01-21 13:59 UTC, merged