Delete dead constant type code in resolver
sorbet/sorbet pull request #5654
Opened 2022-04-19 20:45 UTC by jez

### Motivation

There are no tests for this codepath. I can't think of any tet case that
triggers this codepath. I'd rather just delete it.

### Test plan

See included automated tests.

2022-04-19 21:21 UTC, froydnj requested changes
It looks like we have at least one test case that exercises this codepath?

2022-04-19 21:21 UTC, jez commented
oh beautiful, that's even better.

2022-04-19 22:46 UTC, jez commented
> It looks like we have at least one test case that exercises this codepath?

One of the tests was downstream of another error that is always reported, so the second error is meaningless.

The other one was because in deleting the code I didn't realize that some code was actually important for its side effects, so I've re-introduced that call (to `resolveConstantType`).

2022-04-20 15:49 UTC, froydnj approved these changes

2022-04-20 21:36 UTC, merged