don't pass `defer_vcs: false` on watchman startup
sorbet/sorbet pull request #5735
Opened 2022-05-03 14:43 UTC by froydnj

### Motivation

The watchman documentation for [`defer_vcs`](https://facebook.github.io/watchman/docs/cmd/subscribe.html#filesystem-settling) indicates that, by default, subscription notifications will not be sent until after an outstanding version control notification is complete.  It also says:

> In some circumstances it is desirable for a client to observe the creation of the control files at the start of a version control operation. You may specify that you want this behavior by passing the defer_vcs flag to your subscription command invocation:

which is what Sorbet currently does.

I don't see any reason for Sorbet to do this, and it seems to make far more sense that we should avoid being notified of file changes until after a version control operation is complete.  (Sorbet does not watch for the control files referenced in the watchman documentation.)  Stripe uses watchman in other ways in our development environment and none of these uses, AFAICT, set `defer_vcs: false`.

I guess I can imagine scenarios where you're rebasing or checking out a new branch where with the new regime, we receive one large batch of notifications and therefore take the slow path (too many files changed), but under the old regime, we would have received small numbers of files at a time and therefore could have taken the fast path each time...but this seems unlikely.

### Test plan

See included automated tests.

2022-05-03 16:54 UTC, elliottt approved these changes

2022-05-03 18:06 UTC, jez requested changes
Have we tested this? I don't think we have git on devboxes

2022-06-13 15:22 UTC, froydnj commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Lrz3RLkEy273Ma
→ https://go/builds/bui_Lrz4GK1erqLKCB

2022-06-17 22:10 UTC, jez approved these changes

2022-09-27 14:12 UTC, merged