fix issues with method return types incorrectly resolving on the fast path
sorbet/sorbet pull request #5836
Opened 2022-05-27 15:04 UTC by froydnj

### Motivation

Inspired by work in #5828 and tests in #5805, this fixes one more case where we shouldn't be using existing information in the symbol table.  I said in #5828 that this location would need some kind of context-aware lookup, and this seemed to be the right way to address it.  (The other alternative I could see was to add a `TypeTemplateAliasType` and have a separate dealiasing through that, but that seemed like a lot of work for epsilon gain, if that.)

### Test plan

See included automated tests.

2022-05-27 15:41 UTC, froydnj commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/bui_LlcXq3wUXQUilB
→ https://go/builds/pay-server-sorbet-check--bui_LlcXzJ8K1o79wt

2022-05-31 19:02 UTC, jez commented on test/testdata/lsp/fast_path/method_aliased_result_type.1.rbupdate
> +extend T::Sig
Do you want to put an `# assert-fast-path: true` in this test?

2022-05-31 21:16 UTC, jez commented
I think we can do this without having to introduce new bits onto the symbol table:

https://github.com/sorbet/sorbet/pull/5847

I'm generally -1 on introducing new bits that are redundant with information that is already in the symbol table, as it makes it introduces a point where one of the sources of truth can be updated while forgetting to update the other source of truth.

2022-05-31 21:16 UTC, jez requested changes
https://github.com/sorbet/sorbet/pull/5847

^ curious what you think

2022-05-31 21:44 UTC, jez commented on test/testdata/lsp/fast_path/method_aliased_result_type.1.rbupdate
> +extend T::Sig
moved to #5847

2022-05-31 22:00 UTC, jez approved these changes

2022-05-31 22:01 UTC, merged