WIP - Fix bug in prefix enforcement when no subpackages are present
sorbet/sorbet pull request #5918
Opened 2022-06-16 20:48 UTC by aadi-stripe

### Motivation

### Test plan

See included automated tests.

2022-06-16 21:08 UTC, aadi-stripe commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_LtCKn1RfaFB3jZ
→ https://go/builds/bui_LtCK6yp8247Jk3

2022-06-16 21:55 UTC, aadi-stripe commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_LtD5dkt5lAu6uN
→ https://go/builds/bui_LtD5K8LWRK5srU

2022-06-16 22:45 UTC, ngroman requested changes
Good catch on the bug. I was trying to get very cute. You don't actually need the full equality though, just a length check: I tested this in https://github.com/sorbet/sorbet/commit/2d44c08cf8bc235d6c69017c92add4877e5ea488

2022-06-16 22:45 UTC, ngroman commented on core/packages/PackageInfo.cc
> +}
For future reference, you can compare &vecs with `==`. The std lib is smart enough to include the size check first.

2022-06-17 00:10 UTC, aadi-stripe commented
@ngroman Fixed, thanks!

2022-06-17 15:52 UTC, merged