Add missing URI::Parser, URI::REGEXP
sorbet/sorbet pull request #6327
Opened 2022-09-01 03:41 UTC by notEthan

Ruby defines `URI::Parser` to alias `URI::RFC2396_Parser` (class). Likewise `URI::REGEXP` aliases `URI::RFC2396_REGEXP` (module). Sorbet doesn't appear to know these ([→ sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0AURI%3A%3AParser%0AURI%3A%3AREGEXP)).

I've had a stab at the rbi file, though pretty uncertain I'm anywhere near the correct way to go about defining these aliases (is reopening URI later in the file acceptable? is `T.let` needed for a simple alias?). I'm happy to implement feedback on this, and marked this PR as draft for this reason.

### Motivation

My project uses URI::Parser but sorbet cannot resolve that constant.

### Test plan

I added these to test/testdata/rbi/uri.rb - here too I have low confidence in how correctly I am doing it, and can improve / fix per feedback.

2022-09-01 16:23 UTC, jez commented
> reopening URI later in the file acceptable

The class is defined in the same file as the one you're reopening the class in. Why not simply add the alias above where the other constants in that class are defined?

https://github.com/sorbet/sorbet/blob/32b0f66a170bced4dcf02b08ff30c6ac23615338/rbi/stdlib/uri.rbi#L146

> is `T.let` needed for a simple alias

in fact using `T.let` prevents one of the tests you've added from working (the `T.class_of(...)` one). Simply define the alias like `A = B` and it will be better.

2022-09-01 16:23 UTC, jez requested changes
> reopening URI later in the file acceptable

The class is defined in the same file as the one you're reopening the class in. Why not simply add the alias above where the other constants in that class are defined?

https://github.com/sorbet/sorbet/blob/32b0f66a170bced4dcf02b08ff30c6ac23615338/rbi/stdlib/uri.rbi#L146

> is `T.let` needed for a simple alias

in fact using `T.let` prevents one of the tests you've added from working (the `T.class_of(...)` one). Simply define the alias like `A = B` and it will be better.

2022-09-01 19:03 UTC, notEthan commented
Thanks, updated.

> Why not simply add the alias above

I hadn't because I'd be aliasing a thing that hadn't been defined yet, but I guess that is fine in rbi.

2022-09-02 00:06 UTC, jez approved these changes

2022-09-02 00:06 UTC, merged