ARM Linux builds, cont'd
sorbet/sorbet pull request #6635
Opened 2023-01-01 09:43 UTC by kivikakk

This is a continuation of @ethankhall's work from #6485, rebased and brought up to speed. There is a complimentary PR for the `bazel-toolchain` fork which brings your changes in [sorbet/bazel-toolchain](https://github.com/sorbet/bazel-toolchain/tree/sorbet) up-to-date with [grailbio/bazel-toolchain](https://github.com/grailbio/bazel-toolchain) at XXX.

While Linux ARM builds can be successfully made with this, I haven't quite gotten all the rebasing and rejigging such that _other_ builds are unaffected. I haven't yet tested platform/arch combos outside of Linux/arm64 and Darwin/{x86_64,arm64}.

This is largely due to the change to using `--incompatible_enable_cc_toolchain_resolution`. This appears to be the way forward for Bazel/C++, so I've been trying to work towards getting this working properly.

<details><summary>Build log and test run on Linux arm64</summary>

```
ubuntu-linux-20-04-desktop ~/C/sorbet (ethankhall/arm-build|✔) $ git rev-parse HEAD
d99e80344789b6bc45ae146f5eda30636143ae88
ubuntu-linux-20-04-desktop ~/C/sorbet (ethankhall/arm-build|✔) $ git status
On branch ethankhall/arm-build
Your branch is up to date with 'origin/ethankhall/arm-build'.

nothing to commit, working tree clean
ubuntu-linux-20-04-desktop ~/C/sorbet (ethankhall/arm-build|✔) $ time ../bazelisk clean --expunge
Starting local Bazel server and connecting to it...
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.

________________________________________________________
Executed in    1.18 secs   fish           external
   usr time    6.38 millis  950.00 micros    5.43 millis
   sys time   11.31 millis  481.00 micros   10.83 millis

ubuntu-linux-20-04-desktop ~/C/sorbet (ethankhall/arm-build|✔) $ time ../bazelisk build //main:sorbet --config=release-linux-aarch64 --strip=always
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [static-libs]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Analyzed target //main:sorbet (150 packages loaded, 3733 targets configured).
INFO: Found 1 target...
Target //main:sorbet up-to-date:
  bazel-bin/main/sorbet
INFO: Elapsed time: 652.571s, Critical Path: 144.83s
INFO: 1401 processes: 227 internal, 1174 local.
INFO: Build completed successfully, 1401 total actions

________________________________________________________
Executed in  652.64 secs   fish           external
   usr time   92.83 millis  424.00 micros   92.41 millis
   sys time   50.44 millis  217.00 micros   50.22 millis

ubuntu-linux-20-04-desktop ~/C/sorbet (ethankhall/arm-build|✔) $ bazel-bin/main/sorbet -e "Time.now - nil"
-e:1: Expected Time but found NilClass for argument arg0 https://srb.help/7002
     1 |Time.now - nil
                   ^^^
  Expected Time for argument arg0 of method Time#-:
    https://github.com/sorbet/sorbet/tree/d99e80344789b6bc45ae146f5eda30636143ae88/rbi/core/time.rbi#L358:
     358 |        arg0: Time,
                  ^^^^
  Got NilClass originating from:
    -e:1:
     1 |Time.now - nil
                   ^^^
Errors: 1
ubuntu-linux-20-04-desktop ~/C/sorbet (ethankhall/arm-build|✔) [100] $
```

</details>

cc @tonybruess

### M1 notes

I'm currently testing Darwin builds on an M1 thru Rosetta. **Building from arm64 natively is not yet supported.**

There's a hack included that patches `jemalloc`'s configure step to make this work. This is required because Rosetta 2 doesn't seem to be exposing some information about the emulated architecture's addressing system via `cpuid` correctly; see https://github.com/jemalloc/jemalloc/issues/1997. I haven't yet tested building on native Darwin x86_64 — I do assume it should work OK.

Be warned, if you have a Homebrew-compiled arm64 `python3` on path, attempting to build via Rosetta (e.g. my release build invocation looks like  `arch -x86_64 bazelisk build //main:sorbet --config=release-mac`) will fail in very weird and wonderful ways. `bazel-toolchain`'s host OS detection mechanism calls out to `python3`, and if the system one is on path (i.e. a Universal binary), it will run as whatever arch you invoked bazel as and correctly report accordingly, but if an arm64-only Homebrew built `python3` is on path instead, it'll end up always reporting arm64. Thus the build will proceed with some parts thinking they're x86_64 and other parts arm64, and it's a real mess. I just `brew unlink python3`'d for this one.

<details><summary>Build log and test run on Darwin x86_64 via Rosetta</summary>

```
skye ~/C/sorbet (ethankhall/arm-build|✔) $ git rev-parse HEAD
d99e80344789b6bc45ae146f5eda30636143ae88
skye ~/C/sorbet (ethankhall/arm-build|✔) $ git status
On branch ethankhall/arm-build
Your branch is up to date with 'origin/ethankhall/arm-build'.

nothing to commit, working tree clean
skye ~/C/sorbet (ethankhall/arm-build|✔) $ time arch -x86_64 bazelisk clean --expunge
INFO: Invocation ID: 5088a1c8-4849-4496-b773-cdc7a9812445
INFO: Starting clean.

________________________________________________________
Executed in    2.18 secs      fish           external
   usr time   33.01 millis    0.07 millis   32.94 millis
   sys time   39.61 millis    1.55 millis   38.06 millis

skye ~/C/sorbet (ethankhall/arm-build|✔) $ time arch -x86_64 bazelisk build //main:sorbet --config=release-mac --strip=always
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 113f9ebf-65c7-4602-91e2-bc5c8e8dbdde
INFO: Analyzed target //main:sorbet (151 packages loaded, 3918 targets configured).
INFO: Found 1 target...
INFO: From Compiling gnulib/lib/vasnprintf.c [for host]:
external/m4_v1.4.18/gnulib/lib/vasnprintf.c:3185:35: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
                                  sprintf ((char *) p, "%+d", exponent);
                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
external/m4_v1.4.18/gnulib/lib/vasnprintf.c:3193:35: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
                                  sprintf (expbuf, "%+d", exponent);
                                  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
external/m4_v1.4.18/gnulib/lib/vasnprintf.c:3336:35: warning: 'sprintf' is deprecated: This function is provided for compatibility [...]

2023-01-01 13:49 UTC, froydnj requested changes
I have only skimmed through the patch; this is mostly a notification that building on Linux x86-64 appears to be broken, per CI.  Building with webassembly also needs to work (which would have been tested by CI assuming that the regular x86-64 linux builds passed), and previous efforts to add `--incompatible_enable_cc_toolchain_resolution` in #5228 broke webassembly builds.

I think the bazel-toolchain changes will have to be contributed to the Sorbet fork (or, even better, sent upstream) prior to something like this landing.

Several of the changes rolled up here (e.g. the `tools/config/` changes and what depend on them, the libblake changes, the jemalloc configure hack) could profitably be split out into smaller PRs.

I don't know that we've had a discussion on conditions for merging aarch64 support on Linux or Mac, but one potential blocker is testing aarch64 in CI.  The two options of:

1. Landing something like this PR, but not releasing aarch64 gems; or
2. Landing something like this PR and release untested aarch64 gems.

don't feel like they are huge improvements over the status quo.  I think we do have an aarch64-darwin machine we can attach to buildkite, but that would still leave no way to test aarch64-linux.

2023-01-01 13:49 UTC, froydnj commented on tools/clang.bzl
> +        tool = "@llvm_toolchain_12_0_0//:" + name,
This seems like an unusual change; why is this necessary?

2023-01-01 13:49 UTC, froydnj commented on .buildkite/build-static-release.sh
> +  rbenv exec gem install ../../gems/sorbet-static/sorbet-static-*-$(uname -m)-linux.gem
```suggestion
  rbenv exec gem install ../../gems/sorbet-static/sorbet-static-*-${processor_name}-linux.gem
```

2023-01-01 13:49 UTC, froydnj commented on third_party/externals.bzl
> +    # optimized version of blake2 hashing algorithm
```suggestion
    # optimized version of blake2 hashing algorithm
```

2023-01-01 13:51 UTC, froydnj commented
I was remiss not to say this up front in my review -- thank you for pushing these changes forward!

2023-01-02 19:03 UTC, tonybruess commented
Thank you so much for all your work on this!

2023-02-06 18:17 UTC, twarnock commented
Any progress updates on this?  I would love the solution to just be available so we at least have the option to generate gems on Graviton instances.

2023-02-06 22:51 UTC, kivikakk commented
None — I've been moving house, and catching up on my paid work in-between. I'd love it to be available too, though!

2023-03-08 02:36 UTC, closed without merging

2023-03-08 02:57 UTC, kivikakk commented
The branch can be found here: https://github.com/sorbet/sorbet/compare/master...kivikakk:sorbet:ethankhall/arm-build.