Use cwd from config and expand workspaceFolder
sorbet/sorbet pull request #6702
Opened 2023-02-03 13:50 UTC by paddyobrien

### Motivation

Fixes https://github.com/sorbet/sorbet/issues/6701

There was a previous attempt at fixing this that floundered on variable expansion: https://github.com/sorbet/sorbet/pull/5529

I've done something fairly limited here and just replaced `${workspaceFolder}` with `workspace.rootPath`, this isn't ideal since it other variables won't work, but it has the upside of being backwards compatible.

There doesn't appear to be any API for doing this variable extension properly, at least according to:

https://stackoverflow.com/questions/43972354/how-can-an-extension-expand-configuration-variables-in-vscode

### Test plan

I'm unclear on how to add automated tests for this. I did build the extension and try it out locally. I can confirm it fixed the linked issue.

2023-03-07 18:40 UTC, jez requested changes
This suffers the same problem that the previous attempt suffers from:

https://github.com/sorbet/sorbet/pull/5529#pullrequestreview-928239958

2023-03-08 13:57 UTC, paddyobrien commented
@jez oh yes missed that, updated now.

2023-04-26 03:25 UTC, erickreutz commented
Can we get this merged please?

2023-05-05 16:18 UTC, pbernery commented
Would love to have this merged as well, I am working on a monorepo for which the Gemfile is in a subfolder.

2023-05-29 10:57 UTC, william101 commented
Bump on this PR, would love to get this merged aswell 🙏🏾

2023-09-13 19:45 UTC, carolinar7 commented
bump

2024-01-02 20:11 UTC, filipef101 commented
@jez Can you take a look?

2024-01-07 16:50 UTC, fazo96 commented
Hi, we've been using [a rebased version of this patch](https://github.com/sorbet/sorbet/pull/7484) on our project, and we only found one issue with it (explained in #7484)

It would be awesome to get it merged into master with that bug fixed.

2024-01-17 11:00 UTC, paddyobrien commented
Just as a heads up I'm no longer using sorbet so I won't be progressing this issue any farther.

2024-01-17 11:00 UTC, closed without merging