Fix signature for Kernel.raise
sorbet/sorbet pull request #6982
Opened 2023-05-06 20:13 UTC by iMacTia

### Motivation
`Kernel.raise` second parameter is always optional, as described in the documentation:
> The optional second parameter sets the message associated with the exception 

This is quite useful when re-raising inside a `rescue` block:
```ruby
rescue StandardError => e
  # do something
  raise e
end
```
as it allows to re-raise the captured exception without the need to override the exception message.
I encountered this issue because I'm currently experiencing [the following issue](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20params%28obj_or_str%3A%20T.any%28Exception%2C%20String%29%29.returns%28T.noreturn%29%20%7D%0Adef%20raise_obj_or_string%28obj_or_str%29%0A%20%20raise%20obj_or_str%0Aend) in my code: 
```ruby
sig { params(obj_or_str: T.any(Exception, String)).returns(T.noreturn) }
def raise_obj_or_string(obj_or_str)
  raise obj_or_str
end

# Expected String but found T.any(Exception, String) for argument arg0 https://srb.help/7002
#      6 |  raise obj_or_str
#                 ^^^^^^^^^^
#   Expected String for argument arg0 of method Kernel#raise (overload.1):
#     https://github.com/sorbet/sorbet/tree/master/rbi/core/kernel.rbi#L2913:
#     2913 |        arg0: String,
#                   ^^^^
#   Got T.any(Exception, String) originating from:
#     editor.rb:5:
#      5 |def raise_obj_or_string(obj_or_str)
#                                 ^^^^^^^^^^
# Errors: 1
```

In sorbet's signature overloads for `Kernel.raise`, the third parameter is correctly marked as optional, but not the second.
This change fixes that and adds an additional test for this specific use case.

### Test plan
See included automated tests.

2023-05-06 20:16 UTC, iMacTia commented
Sorry for the direct mention @jez, this is my first contribution so I'm not sure how I'm supposed to "ask a contributor to unblock the tests" 😅

2023-05-07 06:10 UTC, neilparikh commented
@iMacTia I've unblocked them for you. Usually what happens is that whoever ends up reviewing your PR will unblock them for you when they're reviewing it.

You have the following test failure:
```
rbi/core/kernel.rbi#L2920: `T.nilable(T.untyped)` is the same as `T.untyped` https://srb.help/5070 
2920 |        arg1: T.nilable(T.untyped),
```
The second parameter is already marked optional, with this line: `def raise(arg0=T.unsafe(nil), arg1=T.unsafe(nil), arg2=T.unsafe(nil)); end`; `arg1=T.unsafe(nil)` assigned a default value to it. You can verify that with [this example](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aif%20T.unsafe%28false%29%0A%20%20raise%20%22a%22%0Aend%0Aif%20T.unsafe%28false%29%0A%20%20raise%20RuntimeError%0Aend) as well.

2023-05-07 06:35 UTC, iMacTia commented
Thank you @neilparikh!

I'm a bit surprised by the error I'm getting then 🤔.
Do you have any tip on how to make that example work? It seems like Sorbet expects the second parameter to be provided even though it's optional

2023-05-07 12:57 UTC, iMacTia commented
OK I took a step back and did some digging, and I think I better understand the issue now.
This is not a signature issue per-se, but rather a limitation of Sorbet's in using overloaded signatures.
I stumbled on this old issue from 2019: https://github.com/sorbet/sorbet/issues/1483

The issue is the same, there's a variable defined as `T.any(A, B)` which passed to a stdlib method with signature overload that accepts both `A` or `B`. At the moment, sorbet is unable to "test" both scenarios (variable is `A` and variable is `B`) with two different overloaded signatures.

According to the collaborator chiming in, "the complexity of supporting it is tremendous" and "we don't currently intend to fix this limitation".
If that's still the case, then could we instead add a new overloaded signature for the `T.any` scenario(s)?
This should work even if the signature is tested against a subset as I just checked [in this snippet](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20params%28param%3A%20T.any%28Class%2C%20Exception%2C%20String%29%29.void%20%7D%0Adef%20test%28param%29%0A%20%20puts%20param%0Aend%0A%0Asig%20%7B%20params%28param%3A%20T.any%28Exception%2C%20String%29%29.void%20%7D%0Adef%20support%28param%29%0A%20%20test%28param%29%0Aend%0A).

I'm gonna update the PR to try that approach, but any feedback on this is welcome (especially if we're somehow closer to improve Sorbet's management of these cases, in which case we wouldn't need such a workaround)

2023-05-08 13:45 UTC, froydnj requested changes
The initial error you encountered:

```
# Expected String but found T.any(Exception, String) for argument arg0 https://srb.help/7002
#      6 |  raise obj_or_str
#                 ^^^^^^^^^^
#   Expected String for argument arg0 of method Kernel#raise (overload.1):
#     https://github.com/sorbet/sorbet/tree/master/rbi/core/kernel.rbi#L2913:
#     2913 |        arg0: String,
#                   ^^^^
#   Got T.any(Exception, String) originating from:
#     editor.rb:5:
#      5 |def raise_obj_or_string(obj_or_str)
#                                 ^^^^^^^^^^
# Errors: 1
```

is saying that you passed an object that was `T.any(Exception, String)` to `raise`.  But the closest overload Sorbet selected only took `String`, and didn't know anything about `Exception`.  Therefore, Sorbet was telling you that you could potentially be passing an `Exception` to a method that only expects `String`.  It has nothing to do with optionality of the arguments.  #1483 is, I think, only tangentially related.

I think the right thing to do here is to sync up the signatures between `Kernel.fail` and `Kernel.raise` (they are synonyms for the same function under the hood) by replacing the signatures for `Kernel.raise` with the signatures for `Kernel.fail`.  That will at least be much closer to solving the problem.

2023-05-09 11:56 UTC, iMacTia commented
Thank you for rerunning tests, I've noted the issues and I'm fixing them in my branch 👍

2023-05-10 20:05 UTC, froydnj commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Ns3MzHAkRLC2Zz
→ https://go/builds/bui_Ns3MJK6GASk0SV
→ https://go/builds/bui_Ns3MUDIHd4Lksa

2023-05-10 20:27 UTC, froydnj approved these changes
Thank you!  And sorry for not seeing that #1483 was indeed applicable to this situation!

2023-05-10 20:28 UTC, merged

2023-05-11 09:35 UTC, iMacTia commented
No worries @froydnj! I wasn't much clear myself and created more confusion than anything 😅 
Thank you for the support with running tests 🙇