don't call `instance_variable_defined` when it's unnecessary
sorbet/sorbet pull request #6992
Opened 2023-05-09 19:59 UTC by froydnj

### Motivation

Our props code has some patterns of:

```
val = x.instance_variable_get(var) if x.instance_variable_defined?(var)
```

expecting that `val` will be `nil` if the instance variable is defined and the value of the instance variable otherwise.

But this pattern is just wasting work: `instance_variable_get` will already return `nil` if the instance variable does not exist.  `instance_variable_get` will also return nil if `var` is not a valid instance variable name, but since we control the name in this case, we should be able to ensure that `var` always follows the proper format.

(Class variables are different in this respect, and we would absolutely need to check for the existence of class-level variables before access.)

`instance_variable_get` does not cause the variable to spring into existence on the requisite object, so there is no danger of behavior change there.

I realize this is not much of a proof, but if you look in the VM, the codepaths for `instance_variable_get` and `instance_variable_defined?` are practically identical.

This PR, therefore, ditches the `instance_variable_defined?` check.

### Test plan

See included automated tests.  I will run testing on Stripe's codebase before thinking about committing this.

2023-05-09 20:11 UTC, jez requested changes
> But this pattern is just wasting work

I believe this was added by external contributors to silence the "instance variable is not defined" warnings that Ruby will report if you run it in verbose warning mode:

https://github.com/sorbet/sorbet/pull/5482

2025-09-16 16:56 UTC, zanker-stripe commented
> > But this pattern is just wasting work
> 
> I believe this was added by external contributors to silence the "instance variable is not defined" warnings that Ruby will report if you run it in verbose warning mode:
> 
> #5482

I ran into this while looking at some profiling traces, and ran into the same conclusion as @froydnj. Perhaps this got fixed over the last few years accidentally? As far as I can tell, there's no warnings when you remove the `instance_variable_defined?` check.

The only way I can get it to replicate on a console is doing `Foo.allocate.instance_varaible_defined?(:@bar)` but if you're at the point of using `allocate` then 🤷 

```
class Foo < T::Struct
  prop :bar, T.nilable(Integer)
  const :apple, Integer, default: 10
end
=> T::Private::Types::Void::VOID
foo = Foo.new
=> <Foo apple=10 bar=nil>
foo.instance_variable_get(:@bar)
=> nil
foo.instance_variable_defined?(:@bar)
=> true
foo.instance_variable_defined?(:@apple)
=> true
foo.instance_variable_get(:@apple)
=> 10
foo.instance_variable_get(:@bar)
=> nil
```

```
sorbet-runtime(master): RUBYOPT=-w bundle exec rake test
sorbet/gems/sorbet-runtime/bench/enum.rb:43: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:44: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:45: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:47: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:48: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:49: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:51: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:52: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:60: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:61: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:62: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:64: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:65: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:66: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:68: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/bench/enum.rb:69: warning: possibly useless use of == in void context
sorbet/gems/sorbet-runtime/test/types/method_validation.rb:573: warning: key :_ is duplicated and overwritten on line 573
sorbet/gems/sorbet-runtime/test/types/props/serializable.rb:986: warning: assigned but unused variable - msg_string
sorbet/gems/sorbet-runtime/test/types/props/serializable.rb:987: warning: assigned but unused variable - extra_hash
Run options: --seed 2998

# Running:

.....S......................................................................................................................................S.................(eval):2: warning: method redefined; discarding old __t_props_generated_serialize
sorbet/gems/sorbet-runtime/lib/types/props/has_lazily_specialized_methods.rb:93: warning: previous definition of __t_props_generated_serialize was here
(eval):14: warning: method redefined; discarding old __t_props_generated_deserialize
sorbet/gems/sorbet-runtime/lib/types/props/has_lazily_specialized_methods.rb:93: warning: previous definition of __t_props_generated_deserialize was here
....................................................sorbet/gems/sorbet-runtime/test/types/configuration.rb:234: warning: method redefined; discarding old final_method_redefined_ko
sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:257: warning: previous definition of final_method_redefined_ko was here
...........................S....................................................S.............................................................................................................warning: parser/current is loading parser/ruby31, which recognizes 3.1.7-compliant syntax, but you are running 3.1.2.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
...........................................S.................S.............................................sorbet/gems/sorbet-runtime/test/types/final_method.rb:85: warning: method redefined; discarding old foo
sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:257: warning: previous definition of foo was here
....sorbet/gems/sorbet-runtime/test/types/final_method.rb:320: warning: method redefined; discarding old i_am_secretly_final2
sorbet/gems/sorbet-runtime/test/types/final_method.rb:317: warning: previous definition of i_am_secretly_final2 was here
.sorbet/gems/sorbet-runtime/test/types/final_method.rb:184: warning: method redefined; discarding old i_am_secretly_final
sorbet/gems/sorbet-runtime/test/types/final_method.rb:181: warning: previous definition of i_am_secretly_final was here
.sorbet/gems/sorbet-runtime/test/types/final_method.rb:345: warning: method redefined; discarding old i_am_secretly_final2
sorbet/gems/sorbet-runtime/test/types/final_method.rb:337: warning: previous definition of i_am_secretly_final2 was here
..sorbet/gems/sorbet-runtime/test/types/final_method.rb:393: warning: method redefined; discarding old i_am_secretly_final2
sorbet/gems/sorbet-runtime/test/types/final_method.rb:389: warning: previous definition of i_am_secretly_final2 was here
.sorbet/gems/sorbet-runtime/test/types/final_method.rb:257: warning: method redefined; discarding old i_am_secretly_final
sorbet/gems/sorbet-runtime/test/types/final_method.rb:253: warning: previous definition of i_am_secretly_final was here
.sorbet/gems/sorbet-runtime/test/types/final_method.rb:424: warning: method redefined; discarding old foo
sorbet/gems/sorbet-runtime/test/types/final_method.rb:422: warning: previous definition of foo was here
..sorbet/gems/sorbet-runtime/test/types/final_method.rb:235: warning: method redefined; discarding old i_am_secretly_final
sorbet/gems/sorbet-runtime/test/types/final_method.rb:227: warning: previous definition of i_am_secretly_final was here
........sorbet/gems/sorbet-runtime/test/types/final_method.rb:122: warning: method redefined; discarding old foo
sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:257: warning: previous definition of foo was here
.sorbet/gems/sorbet-runtime/test/types/final_method.rb:98: warning: method redefined; discarding old foo
sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:257: warning: previous definition of foo was here
..sorbet/gems/sorbet-runtime/test/types/final_method.rb:209: warning: method redefined; discarding old i_am_secretly_final
sorbet/gems/sorbet-runtime/test/types/final_method.rb:201: warning: previous definition of i_am_secretly_final was here
.sorbet/gems/sorbet-runtime/test/types/final_method.rb:143: warning: method redefined; discarding old i_am_secretly_final
sorbet/gems/sorbet-runtime/test/types/final_method.rb:139: warning: previous definition of i_am_secretly_final was here
......sorbet/gems/sorbet-runtime/test/types/final_method.rb:371: warning: method redefined; discarding old i_am_secretly_final2
sorbet/gems/sorbet-runtime/test/types/final_method.rb:363: warning: previous definition of i_am_secretly_final2 was here
.sorbet/gems/sorbet-runtime/test/types/final_method.rb:279: warning: method redefined; discarding old i_am_secretly_final2
sorbet/gems/sorbet-runtime/test/types/final_method.rb:275: warning: previous definition of i_am_secretly_final2 was here
.sorbet/gems/sorbet-runtime/test/types/final_method.rb:72: warning: method redefined; discarding old foo
sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:257: warning: prev [...]

2025-09-16 19:58 UTC, jez commented on gems/sorbet-runtime/lib/types/props/decorator.rb
> +    val = instance.instance_variable_get(rules[:accessor_key])
Unfortunately, this causes warnings if warnings are enabled.

2025-09-16 20:00 UTC, zanker-stripe commented on gems/sorbet-runtime/lib/types/props/decorator.rb
> +    val = instance.instance_variable_get(rules[:accessor_key])
It causes warnings if they're enabled, but only if you're directly calling `prop_get`. Is that a supported API? At that point I'd wonder if it's worth just having an internal one that won't deal with calling that to avoid the extra calls.

2025-09-16 20:46 UTC, froydnj commented on gems/sorbet-runtime/lib/types/props/decorator.rb
> +    val = instance.instance_variable_get(rules[:accessor_key])
We do support calling `prop_get`, yes; hundreds of uses in pay-server.

Can you elaborate on how this happens, @jez?  I can see that certain kinds of custom decorators might cause problems here, but I don't see how it's a problem for `T::Struct` or even Chalk documents.

2025-09-16 21:50 UTC, jez commented on gems/sorbet-runtime/lib/types/props/decorator.rb
> +    val = instance.instance_variable_get(rules[:accessor_key])
It looks like Ruby 3.0 removed the "instance variable @foo not initialized" warning outright:

https://github.com/ruby/ruby/commit/01b7d5acc702df22d306ae95f1a9c3096e63e624

So this won't repro anymore. Before Ruby 3.0:

```ruby
class A
  def self.main
    @main
  end
end

p(A.main)
```

```
~/sandbox/2.7.2
❯ ruby -w foo.rb
foo.rb:3: warning: instance variable @main not initialized
nil
```

And we had people who [periodically complained](https://github.com/sorbet/sorbet/pull/5482) that Sorbet had spurious instance variable warnings, opening PRs to silence them.

Since they're gone and Sorbet doesn't support 2.7 anymore, we can clean this all up.

2025-09-16 22:03 UTC, merged