Remove excess `is_singleton_method` param
sorbet/sorbet pull request #7533
Opened 2023-12-12 21:09 UTC by amomchilov

This PR is stacked on top of #7531. The new changes are in the last 2 commits.

### Motivation

### Test plan

See included automated tests.

2023-12-13 14:19 UTC, froydnj requested changes
It looks like Rubocop is unhappy with your changes...though honestly, I think Rubocop is wrong in this particular situation, and would be happy to take an override.

2023-12-13 14:32 UTC, amomchilov commented
@froydnj Eh, I'll play ball.

The visual distinction of `self` vs `self.singleton` between `#method_added` and `#singleton_method_added` is nice, but not worth the ugly rubocop exception comment.

Such is the tyranny of the bots 😅

2023-12-14 22:25 UTC, froydnj requested changes
It looks like rebasing is necessary?

2023-12-15 00:32 UTC, amomchilov commented
Interesting, not sure why, as this was just stacked over https://github.com/sorbet/sorbet/pull/7531. Maybe I just made a change there that I didn't reflect here.

Rebased :)

2023-12-18 19:39 UTC, amomchilov commented
Hey @froydnj, any more changes needed here?

2023-12-21 16:47 UTC, froydnj approved these changes
Sorry, I think something must have gone wrong the first time I tried to test this.  Everything passed the second time.  Thanks for your patience!

2023-12-21 16:48 UTC, merged