Add Struct#name
sorbet/sorbet pull request #7646
Opened 2024-02-03 12:49 UTC by dduugg

```
Struct.new(:Foo).name
=> nil
Struct.new('Foo').name
=> "Struct::Foo"
```

### Motivation

Resolves https://sorbet.run/#%23%20typed%3A%20true%0A%0AStruct.new%28%3AFoo%29.name%0AStruct.new%28'Foo'%29.name

2024-02-03 12:51 UTC, froydnj approved these changes

2024-02-03 17:11 UTC, jez requested changes
This method does not exist as an instance method on Struct.

This is simply a limitation in Sorbet’s support for Struct.new.

The result of Struct.new is not an instance of Struct but rather a T.class_of(Struct). Fixing this properly so that the name method is available requires overriding the definition of def self.new in Struct to return something other than T.attached_class (probably T.class_of(Struct))

2024-02-03 17:33 UTC, dduugg commented
> This method does not exist as an instance method on Struct.
> 
> This is simply a limitation in Sorbet’s support for Struct.new.
> 
> The result of Struct.new is not an instance of Struct but rather a T.class_of(Struct). Fixing this properly so that the name method is available requires overriding the definition of def self.new in Struct to return something other than T.attached_class (probably T.class_of(Struct))

Ooh, good catch, and tricky, because the `Struct` that's returned has a different constructor, which returns an instance, e.g.:
```
Struct.new('Foo', :foo, :bar).new(1, 2)
=> #<struct Struct::Foo foo=1, bar=2>
```
Do you have suggestions for capturing this most effectively with Sorbet?

2024-02-04 10:20 UTC, dduugg commented
I've updated the PR so that `Struct.new` returns `T.untyped`.

(There is also an instance method `new` [elsewhere](https://github.com/sorbet/sorbet/blob/f6d54ab/rbi/core/struct.rbi#L209) in the file, which does something similar, but may be in error)

2024-02-05 05:23 UTC, closed without merging