[wip] Attempt to get libffi wired up to build fiddle
sorbet/sorbet pull request #7711
Opened 2024-02-16 16:05 UTC by jd-stripe

### Motivation

### Test plan

See included automated tests.

2024-02-19 12:38 UTC, jd-stripe commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_PahVAx8ZJDBvty
→ https://go/builds/bui_PahWHOuWN5Ncr8
→ https://go/builds/bui_PahWvKx5pn4Jau

2024-02-19 12:42 UTC, jd-stripe commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Pahac7yDIFubab
→ https://go/builds/bui_PahaM4Jy4bdGV6
→ https://go/builds/bui_Pahaema9OsSd1m

2024-03-14 20:24 UTC, fable-stripe requested changes

2024-03-14 20:24 UTC, fable-stripe commented on third_party/ruby/build-ruby.bzl
> +# rm -rf "$build_dir"
do we sitll need this?

2024-03-14 20:24 UTC, fable-stripe commented on third_party/ruby/ldflags.patch
> ++  libffi.ldflags = RbConfig.expand("$(LDFLAGS) #{libpathflag([relative_from($topdir, "..")])}".dup)
what does this change?

2024-03-20 13:43 UTC, fable-stripe commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_PlxLg0bli12ju0
→ https://go/builds/bui_PlxLOmtfubyIZY
→ https://go/builds/bui_PlxLX4ELb9gbju

2024-03-20 14:33 UTC, fable-stripe commented
Stripes can see https://cibot.corp.stripe.com/build_groups/bg_PlxfRlI3wrggMN

tested that fiddle is functional.
```
:hamburger: fable@fable-doing-ruby-crimes:/pay/src/sorbet$ cat hi.rb
require 'fiddle'


libm = Fiddle.dlopen('./libfoo.so')

floor = Fiddle::Function.new(
  libm['add1'],
  [Fiddle::TYPE_INT],
  Fiddle::TYPE_INT
)

puts floor.call(3)

:hamburger: fable@fable:/pay/src/sorbet$ bazel-bin/external/sorbet_ruby_3_3/ruby hi.rb 
4
```

2024-03-20 14:50 UTC, fable-stripe commented
r? @froydnj-stripe

2024-03-20 14:56 UTC, merged