Add `-march=armv8.1a` for linux-aarch64 builds
sorbet/sorbet pull request #7933
Opened 2024-06-03 21:23 UTC by maruth-stripe

### Motivation

https://github.com/sorbet/sorbet/issues/7932

### Test plan

Built locally on a Graviton machine. Disassembly of binary had `ldadd*` family of instructions, introduced in v8.1a. typecheck succeeded.

2024-06-03 21:28 UTC, maruth-stripe commented
All the aarch64 machines we use are all at least ARM v8.2a. Ideally if we had aarch64 builds for macs we could enable this for that as well, but alas

2024-06-03 21:35 UTC, jez commented
Is this going to break any open source users attempting to run Sorbet on older arm hardware?

2024-06-03 21:35 UTC, jez requested changes
^

2024-06-04 04:16 UTC, maruthgoyal commented
This will work for Graviton2+ and Apple M1+. I'm not aware of any other major ARM chips used on laptop/server hardware. Graviton 1 is not offered by AWS anymore far as I can tell.

2024-06-04 18:50 UTC, jez approved these changes

2024-06-04 19:57 UTC, merged