Delete `CompiledLevel`
sorbet/sorbet pull request #8069
Opened 2024-08-02 05:57 UTC by neilparikh

### Motivation

Compiler is deleted.

### Test plan

Existing tests + running over Stripe's codebase.

2024-08-02 05:58 UTC, neilparikh commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_QaPJ2l7F48hK2k
→ https://go/builds/bui_QaPKAlRcIsicro
→ https://go/builds/bui_QaPKt7BlfsI2Z9

2024-08-02 17:06 UTC, jez commented on test/testdata/rewriter/chalk_odm_document_compiled.rb
It was intentional to keep the compiler tests when we deleted the compiler, they're still also tests of Sorbet itself.

2024-08-02 17:08 UTC, jez commented on proto/File.proto
We should never delete fields from proto files, because proto is designed for compatibility.

2024-08-02 17:10 UTC, jez commented on class_flatten/class_flatten.cc
Is there not more we can do here? It seems like replacement is always empty tree now, which suggests that we can keep folding code away.

2024-08-02 17:12 UTC, jez commented on core/proto/proto.cc
> -        entry->set_compiled(compiledToProto(file.data(gs).compiledLevel));
IMO we should keep this line, and set it to None unconditionally. This is the default, but it's nice to be explicit.

2024-08-02 17:12 UTC, jez requested changes
^

2024-08-05 23:50 UTC, neilparikh commented on test/testdata/rewriter/chalk_odm_document_compiled.rb
I agree in general. In this case, I diffed the test and exp trees with and without the `_compiled` and they were identical (except for the `compiled: true` line), so the `_compiled` versions of the tests aren't actually testing anything new.

2024-08-06 00:01 UTC, jez commented on test/cli/file-sigils-json/test.sh
I believe this test is the canonical test of the `--print file-table-json` output.

We should not delete this CLI test.

2024-08-06 00:03 UTC, jez commented on resolver/resolver.cc
> -        cnst->symbol = core::Symbols::Sorbet_Private_Static_ResolvedSig();
Does this mean we can delete `Sorbet_Private_Static_ResolvedSig` now?

2024-08-06 00:05 UTC, jez commented
One request to undelete a CLI test, and one suggestion that we might be able to delete more.

2024-08-06 21:23 UTC, jez approved these changes

2024-08-06 21:28 UTC, neilparikh commented
We have a policy of testing changes to Sorbet against Stripe's codebase before
merging them. I've kicked off a test run for the current PR.  When the build
finishes, I'll share with you whether or how it failed. Thanks!

Stripe employees can see the build results here:

→ https://go/builds/bui_Qc9DLJ6QjOPcru
→ https://go/builds/bui_Qc9Dii5yVtrdqj
→ https://go/builds/bui_Qc9DMZebiz1iWh

2024-08-06 21:47 UTC, merged