Prevent crash when including `::Array` in`::Module`
sorbet/sorbet pull request #8333
Opened 2024-11-27 17:58 UTC by jwinr

The resolver previously crashed when attempting to include `::Array` in `::Module`. This change adds a check within the `addMixin` logic in `resolveAncestorJob` to specifically handle `Array` when validating includes. This prevents an invalid type construction that would lead to a sanity check failure during type inference.
 
### Motivation
Fixes #8208 

### Test plan

See included automated tests.

2024-11-27 21:22 UTC, jez requested changes
Hm, it’s very suspect to solve this crash by hard coding the name of a class in the standard library. Are we sure that this fixes the root cause of the bug? Does the bug not reproduce with any other class? Have we investigated which part of mentioning Array here is causing the problem?

for example, my suspicion is that the crash would manifest with _any_ generic class, not just Array.

We need to do some more digging here.

2024-11-30 03:13 UTC, jwinr commented
Very fair point about it being suspect, which turned out to be right, because it did crash with other generic classes. Apologies for overlooking that and making an assumption. The real issue was due to Sorbet incorrectly inheriting type members like `Elem` and `K, V` from generic classes that were propagating through includes. My proposed solution is a check for `core::Symbols::Module()` to prevent inheriting type members in `resolveTypeMembers`. This handles `Array` or any other generic type. I've tested this with various generic classes and the original crash no longer occurs, but I'm happy to look into this even further if you believe there's a better solution.

2024-12-13 02:09 UTC, jwinr commented
I really appreciate the extra info here. After spending some time digging into the issue, I think I can now explain it more clearly. You mentioned that during error recovery, Sorbet doesn’t invalidate the `externalType` cache. I tried to fix this by invalidating or recalculating the cached `externalType` when a `type_member` is modified. However, this led to a different error:

```bash
Error: Type Elem declared by parent T.class_of(Object) must be re-declared in T.class_of(<root>)
```

What I ended up finding is that when a class includes multiple mixins that share an inheritance path (like `Module` including `Array` which includes `Enumerable`), type members like `Elem` were being processed multiple times through different paths. I'm proposing a new solution that matches Ruby's method resolution order and fixes both the `AppliedType` argument mismatch and the redeclaration errors without needing special cases for specific symbols. We check if a mixin inherits from another mixin we'll process later, skip type member propagation in that case, and let the original source (e.g. `Enumerable`) handle the type member declaration. So basically, during error recovery, `Module` skips `Array`'s `Elem`, getting it from `Enumerable`. `T.class_of(Array)` stays at 1 member, and the cache remains valid because type members never duplicate. I'm hoping this feels like a more sensible approach!

2025-01-10 18:31 UTC, jez reviewed
Hey sorry for the long turnaround.

I still stand by what I said in my previous review:

> This bug is pretty subtle, and I don't really know what the best fix for this would be.

The implementation in this PR doesn't strike me as the right solution—it's accidentally quadratic in a symbol's mixins in a particularly performance sensitive portion of Sorbet.

I'm convinced that given enough time, I would be able to find a solution that doesn't suffer from that property, but I don't have time to spend on this particular crash at the moment. I don't know that there's a way forward on this without someone else who has time to offer more in-depth Sorbet expertise.

2025-01-11 18:03 UTC, jwinr commented
No worries at all about the turnaround—I really appreciate the time and thought you've put into this. Given everything I've tried along with your feedback, I think it's best for me to step away from this issue for now. Hopefully, what I've shared along with your notes can help steer someone toward the right solution. Maybe as I work on other issues, I'll come up with a better approach myself. (I'd like to be optimistic, anyway.) Thanks for your patience on this.

2025-01-11 18:03 UTC, closed without merging